server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/webScrapper/resources/what_to_eat.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: sa
  jpa:
    database-platform: com.mb.application.dialect.SQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
debug: true